server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone:  http://eureka.server1.com:8083/eureka/,http://eureka.server2.com:8084/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:tongrongbing/micorservicecloud-config.git


