server:
  port: 8085
eureka:
  instance:
    hostname: eureka.server3.com  #eureka服务端的实例名称

  client:
    register-with-eureka: false #不注册自己
    fetch-registry: false #不用去检索服务
    service-url:
      defaultZone:  http://eureka.server1.com:8083/eureka/,http://eureka.server2.com:8084/eureka/