spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb02?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microserviceloud-dept
  jpa:
    show-sql: true
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone:  http://eureka.server1.com:8083/eureka/,http://eureka.server2.com:8084/eureka/
  instance:
    instance-id: myzuul.com
    prefer-ip-address: true
info:
  app.name: microserviceloud-dept8001
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}
