spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: microserviceloud-dept
  jpa:
    show-sql: true
server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone:  http://eureka.server1.com:8083/eureka/,http://eureka.server2.com:8084/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
info:
  app.name: microserviceloud-dept
  build.artifactId: ${project.artifactId}
  build.version:  ${project.version}
